name: Build and Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev build-essential

    - name: Clean and prepare build directory
      run: |
        rm -rf build
        mkdir -p build

    - name: Build
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make
        ctest --output-on-failure

    - name: Create DEB package
      run: |
        cd build
        cpack -G DEB

    - name: Create Git Tag
      uses: actions/github-script@v6
      with:
        script: |
          const tag = `v1.0.0-${process.env.GITHUB_RUN_NUMBER}`;
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/${tag}`,
            sha: context.sha
          });
          return tag;

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0-${{ github.run_number }}
        files: build/*.deb
